# Generated by Django 2.1.1 on 2018-09-20 08:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_auto_20180920_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='timestamp',
            field=models.DateTimeField(verbose_name=datetime.datetime(2018, 9, 20, 8, 36, 51, 561486, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='joined_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
