# Generated by Django 2.1.1 on 2018-09-20 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_auto_20180920_0837'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'default_permissions': ('add', 'view')},
        ),
    ]
