# Generated by Django 2.1.1 on 2018-09-21 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_token'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-timestamp',)},
        ),
    ]
