# Generated by Django 2.1.1 on 2018-09-23 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0019_auto_20180922_2258'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='relationship',
            unique_together={('from_user', 'to_user')},
        ),
    ]
